FROM python:3.11-slim-buster

WORKDIR /app

RUN pip install --upgrade pip
COPY ./requirements.txt .
COPY ./requirements-worker.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements-worker.txt

COPY . .

ENV C_FORCE_ROOT=1

CMD ["celery", "--app=worker.app", "worker", "--loglevel=info", "-B"]