"""empty message

Revision ID: 052e81b7347f
Revises: b18df26f02b8
Create Date: 2023-05-13 08:28:23.745575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '052e81b7347f'
down_revision = 'b18df26f02b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth2token', 'access_token',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('oauth2token', 'refresh_token',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth2token', 'refresh_token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=48),
               existing_nullable=True)
    op.alter_column('oauth2token', 'access_token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=48),
               existing_nullable=False)
    # ### end Alembic commands ###