"""Cascade on delete

Revision ID: 49557398208a
Revises: d8b6f35646e2
Create Date: 2024-09-28 10:00:37.548701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '49557398208a'
down_revision = 'd8b6f35646e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eventsubscription_user_uuid_fkey', 'eventsubscription', type_='foreignkey')
    op.create_foreign_key(None, 'eventsubscription', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('membership_team_uuid_fkey', 'membership', type_='foreignkey')
    op.drop_constraint('membership_user_uuid_fkey', 'membership', type_='foreignkey')
    op.create_foreign_key(None, 'membership', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'membership', 'team', ['team_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('oauth2token_user_id_fkey', 'oauth2token', type_='foreignkey')
    op.create_foreign_key(None, 'oauth2token', 'user', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('teaminvite_team_uuid_fkey', 'teaminvite', type_='foreignkey')
    op.create_foreign_key(None, 'teaminvite', 'team', ['team_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teaminvite', type_='foreignkey')
    op.create_foreign_key('teaminvite_team_uuid_fkey', 'teaminvite', 'team', ['team_uuid'], ['uuid'])
    op.drop_constraint(None, 'oauth2token', type_='foreignkey')
    op.create_foreign_key('oauth2token_user_id_fkey', 'oauth2token', 'user', ['user_id'], ['uuid'])
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.create_foreign_key('membership_user_uuid_fkey', 'membership', 'user', ['user_uuid'], ['uuid'])
    op.create_foreign_key('membership_team_uuid_fkey', 'membership', 'team', ['team_uuid'], ['uuid'])
    op.drop_constraint(None, 'eventsubscription', type_='foreignkey')
    op.create_foreign_key('eventsubscription_user_uuid_fkey', 'eventsubscription', 'user', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###