"""empty message

Revision ID: 4d8926339771
Revises: 61048a8771e3
Create Date: 2023-04-08 20:25:03.208245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4d8926339771'
down_revision = '61048a8771e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_team_uuid'), 'team', ['uuid'], unique=False)
    op.create_table('membership',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('team_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('allowed_invites', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_uuid'], ['team.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('team_uuid', 'user_uuid')
    )
    op.add_column('user', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superadmin')
    op.drop_table('membership')
    op.drop_index(op.f('ix_team_uuid'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###