"""empty message

Revision ID: 56123a610508
Revises: 4d8926339771
Create Date: 2023-04-08 20:31:45.300207

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '56123a610508'
down_revision = '4d8926339771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaminvite',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('team_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_twitch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['team_uuid'], ['team.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_teaminvite_uuid'), 'teaminvite', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaminvite_uuid'), table_name='teaminvite')
    op.drop_table('teaminvite')
    # ### end Alembic commands ###