"""empty message

Revision ID: 61048a8771e3
Revises: 
Create Date: 2023-04-02 19:56:32.296881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '61048a8771e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('discord_channel_id', sa.String(length=64), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_server_uuid'), 'server', ['uuid'], unique=False)
    op.create_table('twitchmessageid',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_twitchmessageid_uuid'), 'twitchmessageid', ['uuid'], unique=False)
    op.create_table('user',
    sa.Column('discord_id', sa.String(length=64), nullable=True),
    sa.Column('twitch_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('login_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('offline_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('twitch_id')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=False)
    op.create_table('eventsubscription',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('server_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['server_uuid'], ['server.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_eventsubscription_uuid'), 'eventsubscription', ['uuid'], unique=False)
    op.create_table('oauth2token',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.String(length=48), nullable=False),
    sa.Column('refresh_token', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_oauth2token_uuid'), 'oauth2token', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2token_uuid'), table_name='oauth2token')
    op.drop_table('oauth2token')
    op.drop_index(op.f('ix_eventsubscription_uuid'), table_name='eventsubscription')
    op.drop_table('eventsubscription')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_twitchmessageid_uuid'), table_name='twitchmessageid')
    op.drop_table('twitchmessageid')
    op.drop_index(op.f('ix_server_uuid'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###