"""empty message

Revision ID: b18df26f02b8
Revises: f84545c07861
Create Date: 2023-05-13 08:23:51.749238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b18df26f02b8'
down_revision = 'f84545c07861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###