"""External IDs to int

Revision ID: bc7c3f9218e5
Revises: 052e81b7347f
Create Date: 2024-09-01 15:23:03.919889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bc7c3f9218e5'
down_revision = '052e81b7347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventsubscription', 'server_discord_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=False, postgresql_using='server_discord_id::bigint')
    op.alter_column('eventsubscription', 'channel_discord_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=False, postgresql_using='channel_discord_id::bigint')
    op.alter_column('server', 'discord_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.BigInteger(),
               existing_nullable=False, postgresql_using='discord_id::bigint')
    op.alter_column('server', 'discord_channel_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.BigInteger(),
               existing_nullable=True, postgresql_using='discord_channel_id::bigint')
    op.alter_column('user', 'discord_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.BigInteger(),
               existing_nullable=True, postgresql_using='discord_id::bigint')
    op.alter_column('user', 'twitch_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.BigInteger(),
               existing_nullable=False, postgresql_using='twitch_id::bigint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'twitch_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('user', 'discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('server', 'discord_channel_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('server', 'discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('eventsubscription', 'channel_discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('eventsubscription', 'server_discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###