"""Add message field to eventsubs

Revision ID: d8b6f35646e2
Revises: bc7c3f9218e5
Create Date: 2024-09-01 18:59:41.401887

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd8b6f35646e2'
down_revision = 'bc7c3f9218e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventsubscription', sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventsubscription', 'message')
    # ### end Alembic commands ###