"""empty message

Revision ID: f84545c07861
Revises: 56123a610508
Create Date: 2023-05-11 17:55:04.077838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f84545c07861'
down_revision = '56123a610508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventsubscription', sa.Column('server_discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('eventsubscription', sa.Column('channel_discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('eventsubscription', sa.Column('twitch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('eventsubscription_server_uuid_fkey', 'eventsubscription', type_='foreignkey')
    op.drop_column('eventsubscription', 'server_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventsubscription', sa.Column('server_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('eventsubscription_server_uuid_fkey', 'eventsubscription', 'server', ['server_uuid'], ['uuid'])
    op.drop_column('eventsubscription', 'twitch_id')
    op.drop_column('eventsubscription', 'channel_discord_id')
    op.drop_column('eventsubscription', 'server_discord_id')
    # ### end Alembic commands ###